spring:
  datasource:
    url: 'jdbc:mariadb://localhost:3306/hostel_manager'
    jdbc-url: 'jdbc:mariadb://localhost:3306/hostel_manager'
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
server:
  error:
    include-binding-errors: always
    include-message: always